[project]
name = "etl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-cloud-bigquery>=3.38.0",
    "prefect>=3.4.24",
    "prefect-gcp>=0.6.11",
]
